version: '3.5'

services:
  postgres:
    container_name: hrp-postgres
    image: postgres:14.5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_MULTIPLE_DATABASES: "${POSTGRES_DB:-healthstack}, ${POSTGRESQL_DATABASE_NAME:-supertokens}, ${POSTGRESQL_TOKENS_DB:-tokens}"
    volumes: 
      - ./multi_db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - hrp
    restart: unless-stopped
  supertokens:
    container_name: hrp-supertokens
    image: supertokens/supertokens-postgresql
    depends_on:
        - postgres
    environment:
        POSTGRESQL_USER: ${POSTGRESQL_USER:-postgres}
        POSTGRESQL_HOST: ${POSTGRESQL_HOST:-hrp-postgres}
        POSTGRESQL_PORT: ${POSTGRESQL_PORT:-5432}
        POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD:-password}
        POSTGRESQL_DATABASE_NAME: ${POSTGRESQL_DATABASE_NAME:-supertokens}
    ports:
        - "3567:3567"
    networks:
        - hrp
  account-service:
    container_name: hrp-account-service
    image: account-service
    depends_on:
        - supertokens
    build: backend-system/account-service/
    environment:
        SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
        SMTP_PORT: ${SMTP_PORT:-465}
        MAIL_USER: ${MAIL_USER:-testl@gmail.com}
        MAIL_USER_PASSWORD: ${MAIL_USER_PASSWORD:-PasswordTest}
        SUPER_TOKEN_URL: ${SUPER_TOKEN_URL:-http://hrp-supertokens:3567}
        JWK_URL: ${JWK_URL:-http://hrp-supertokens:3567/recipe/jwt/jwks}
        DB_URL: ${DB_URL:-hrp-postgres:5432}
        DB_USERNAME: ${POSTGRESQL_USER:-postgres}
        DB_PASSWORD: ${POSTGRES_PASSWORD:-password}
        DB_NAME: ${POSTGRESQL_TOKENS_DB:-tokens}
    ports:
        - "8081:8080"
    networks:
        - hrp 
  platform:
    container_name: hrp-platform
    image: hrp-platform
    depends_on:
        - postgres
    build: backend-system/platform/    
    environment:
        DB_HOST: ${DB_HOST:-hrp-postgres}
        DB_USERNAME: ${POSTGRESQL_USER:-postgres}
        DB_PASSWORD: ${POSTGRES_PASSWORD:-password}
        DB_PORT: ${POSTGRESQL_PORT:-5432}
        DB_NAME: ${POSTGRES_DB:-healthstack}
        DB_SCHEMA: ${DB_SCHEMA:-public}
        GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-service-account-key.json}
        JWK_URL: ${JWK_URL:-http://hrp-supertokens:3567/recipe/jwt/jwks}
        ACCOUNT_SERVICE_URL: ${ACCOUNT_SERVICE_URL:-http://hrp-account-service:8081}
    ports:
        - "3030:3030"
    networks:
      - hrp
  trino:
    container_name: hrp-trino
    image: trinodb/trino:402
    depends_on:
        - postgres
    ports:
        - "8080:8080"
    volumes:
        - ./rule-update/:/etc/trino/access-control/
        - ./trino/etc/jvm.config:/etc/jvm.config
        - ./trino/etc/catalog/postgresql/postgresql.properties:/etc/trino/catalog/postgresql.properties
    networks:
        - hrp
  data-query-service:
    container_name: hrp-data-query-service
    image: hrp-data-query-service
    depends_on:
        - trino
    build: backend-system/data-query-service/
    environment:
        TRINO_CATALOG: ${TRINO_CATALOG:-postgresql}
        TRINO_HOST: ${TRINO_HOST:-hrp-trino}
        TRINO_PORT: ${TRINO_PORT:-8080}
        JWK_URL: ${JWK_URL:-http://hrp-supertokens:3567/recipe/jwt/jwks}
    ports:
        - "3031:3030"
    networks:
        - hrp
  trino-rule-update-service:
    container_name: hrp-trino-rule-update-service
    image: trino-rule-update-service
    build: backend-system/trino-rule-update-service/
    environment:
        FIXED_DELAY_MILLISEC: ${FIXED_DELAY_MILLISEC:-5000}
        ACCOUNT_SERVICE_URL: ${ACCOUNT_SERVICE_URL:-http://hrp-account-service:8080}
    depends_on:
        - account-service
    volumes:
        - ./rule-update/rules.json:/etc/trino/access-control/rules.json
    networks:
        - hrp
  haproxy:
    image: haproxy:2.6.6
    container_name: hrp-balancer
    ports:
      - "3035:3035"
      - "8404:8404"
    volumes:
        - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        - ./haproxy/404.http:/usr/local/etc/haproxy/errors/404.http:ro
        - ./haproxy/cors-origins.lst:/usr/local/etc/haproxy/cors-origins.lst:ro
        - ./haproxy/cors.lua:/usr/local/etc/haproxy/cors.lua:ro
    depends_on:
        - account-service
        - platform
        - data-query-service
    networks:
      - hrp
    restart: unless-stopped       
networks:
  hrp:
    driver: bridge